# CircleCI configuration file

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
            name: Build
            command: mvn -B -DskipTests clean package

      - run:
            name: Test
            command: mvn test

      - run:
          name: Upload coverage data to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}

      - run:
          name: Code Coverage
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov

      - run:
          name: site
          command: mvn site

      - run:
          name: post
          command: mvn post-site

      - store_artifacts:
          path: target/site/jacoco/jacoco.xml
          destination: /tmp/artifacts

      - store_artifacts:
          path: target/site/badges/checkstyle-result.svg
          destination: /tmp/artifacts

      - add_ssh_keys:
          fingerprints:
            - "63:fc:c2:91:99:64:32:4b:51:1b:d4:fa:bf:f8:5c:70"

      - run:
          name: javadoc
          command:
            mvn javadoc:javadoc
      - run:
          name: deploy
          command: |
            git config --global user.name "GabrielDesbouis"
            git config --global user.email "gabriel.desbouis@alumni.univ-avignon.fr"
            git clone --branch=gh-pages --depth=1 git@github.com:GabrielDesbouis/ceri-m1-techniques-de-test.git gh-pages
            rm -rf gh-pages/*
            cp -R target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "Javadoc Updated"
            git push origin gh-pages
workflows:
  verification:
    jobs:
      - build-and-test:
            filters:
                branches:
                  only:
                    - master
# FIN TP4