# CircleCI configuration file

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
            name: Build
            command: mvn -B -DskipTests clean package

      - run:
            name: Test
            command: mvn test

      - store_artifacts:
          path: target/site/jacoco/jacoco.xml
          destination: /tmp/artifacts

      - run:
          name: Upload coverage data to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
      - run:
          name: Code Coverage
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov; chmod +x codecov; ./codecov
workflows:
  verification:
    jobs:
      - build-and-test:
            filters:
                branches:
                  only:
                    - master

# FIN TP4