# CircleCI configuration file

version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.1
    steps:
      - checkout
      - run:
            name: Build
            command: mvn -B -DskipTests clean package

      - run:
            name: Test
            command: mvn test

workflows:
  verification:
    jobs:
      - build-and-test:
            filters:
                branches:
                  only:
                    - master

# FIN TP2